---
title: "p8105_hw5_cl4043"
author: "Stella Li"
date: "11/11/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(purrr)
library(stringr)
```

## Problem 1

```{r cars message=FALSE, warning=FALSE}
homicide_df = 
  read_csv("./data/homicide_data.csv") %>%
  mutate( city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved",
    )
  ) %>%
  filter(city_state != "Tulsa_AL") %>%
  select(city_state, resolved)
```
looking at the table


```{r}
agg_df = homicide_df %>%
  group_by(city_state) %>%
  summarize(hom_total = n(),
            hom_unsolved = sum(resolved == "unsolved")
            )
```

prop test on single city

```{r}

prop.test(
  agg_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  agg_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
  broom::tidy()


results_df = 
  agg_df%>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x=.x, n= .y)), tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y= estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

```{r, message = FALSE}
path_df = 
  tibble(
    path = list.files("lda_data"),) %>%
  mutate(
    path = str_c("lda_data/", path),
    data = map(path, read_csv)) %>%
  unnest(data) %>%
  mutate(group = substr(path, 20, 22), id = substr(path, 24, 25), id = str_c(group, id)) %>%
  select(-path) %>%
  pivot_longer(week_1:week_8, names_to = "week", names_prefix = "week_", values_to = "obs") %>%
  mutate(week = as.factor(week), id = as.factor(id))%>% group_by(id)
path_df %>%
  ggplot(aes(x = week, y = obs, group = id, color = group)) +
  geom_line() +
  labs(
    title = "Observations for Each Subject Over 8 Weeks",
    x = "Week Number",
    y = "Observation Value")

```


## Problem 3

```{r}

```

